drop table user if exists;
create table user (
  user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null,
  email varchar(50) not null,
  pw varchar(255) not null
);

drop table expression if exists;
create table expression (
  expression_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  user_id integer not null,
  expression varchar(160) not null,
  result varchar(160) not null,
  pub_date timestamp
);